# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [57]:
mat = np.array([[1,2,3,4,5,6]]).reshape(2,3)
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [4]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [5]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [6]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [7]:

vec4 = np.linspace(0,9,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [16]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [18]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,mat)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[[ 10  20  28]
 [ 33 105 130]
 [ 42 114 154]]


In [19]:
print(np.linalg.solve(mat,product))
print('')
mat5 = np.linalg.inv(mat)
print(mat5)
print(np.matmul(mat5,product))

[[1. 2. 1.]
 [4. 5. 9.]
 [1. 8. 9.]]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]
[[1. 2. 1.]
 [4. 5. 9.]
 [1. 8. 9.]]


In [20]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [21]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.30698989 0.77409727 0.48652808 0.42725428 0.18213536]
 [0.65700648 0.2905624  0.97689239 0.97315315 0.98660056]
 [0.76578037 0.30661008 0.04812579 0.39116089 0.4454898 ]
 [0.68007601 0.86726295 0.81696144 0.61089724 0.01390145]
 [0.19225491 0.59980955 0.18022269 0.0346622  0.77481657]]

[[ 1.21695756e+00 -1.18241754e-01 -9.48563952e-01 -1.52649792e+00
   4.60932134e-01]
 [-3.05635602e-01  3.64571400e-01  3.41233059e+00 -1.88684315e-01
   8.63644988e-01]
 [ 1.41127607e+00  1.45332478e+00 -2.81095333e-01  6.81504368e-01
  -6.26093855e-01]
 [ 1.40172516e-01  1.07301711e+00 -1.74393395e-01 -5.89837811e-01
  -7.56544591e-01]
 [-8.04377659e-01 -1.45935901e+00  5.93375795e-01 -1.14962623e+00
   6.11237207e-01]
 [ 2.58666004e-01  2.14524081e+00 -3.25760557e-01  8.31785062e-03
   1.74812453e+00]
 [-8.39316076e-01 -5.23431497e-01 -6.84859388e-01  1.01522307e+00
   1.98293087e-01]
 [-7.40300803e-01  2.37963283e-03 -6.01001789e-01 -3.13229859e-01
   9.01815999e-01]
 [-4.94779105e-01 -3.1207733

In [22]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5115700716590206
0.9988793075666763


In [23]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.01390145072096649
3.41233059195473


In [24]:
# break here for next video!

In [25]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.33151922  0.61175809 -1.04881602  0.8204043  -0.84512561  0.98925304
  1.04673877  0.83416121  0.30278809  1.55889453 -0.40725985  0.28619714
  0.74521579 -0.41329877 -0.40419343 -0.07294411  2.12135945  0.40525123
 -1.27204849]
1.0467387681338518


In [26]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-0.84512561  0.98925304  1.04673877  0.83416121  0.30278809]


In [27]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[0.33151922 0.8204043  1.04673877 1.55889453 0.74521579]


In [28]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.30698989 0.77409727 0.48652808 0.42725428 0.18213536]
 [0.65700648 0.2905624  0.97689239 0.97315315 0.98660056]
 [0.76578037 0.30661008 0.04812579 0.39116089 0.4454898 ]
 [0.68007601 0.86726295 0.81696144 0.61089724 0.01390145]
 [0.19225491 0.59980955 0.18022269 0.0346622  0.77481657]]
0.9768923854097535
0.9768923854097535


In [29]:
print(rand_mat[0:2,1:3])

[[0.77409727 0.48652808]
 [0.2905624  0.97689239]]


In [30]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.33151922  0.61175809 -1.04881602  0.8204043  -0.84512561  0.98925304
  1.04673877  0.83416121  0.30278809  1.55889453 -0.40725985  0.28619714
  0.74521579 -0.41329877 -0.40419343 -0.07294411  2.12135945  0.40525123
 -1.27204849]

[ 0.33151922  0.61175809 -1.04881602  4.          4.          0.98925304
  1.04673877  0.83416121  0.30278809  1.55889453 -0.40725985  0.28619714
  0.74521579 -0.41329877 -0.40419343 -0.07294411  2.12135945  0.40525123
 -1.27204849]

[ 0.33151922  0.61175809 -1.04881602  1.          2.          0.98925304
  1.04673877  0.83416121  0.30278809  1.55889453 -0.40725985  0.28619714
  0.74521579 -0.41329877 -0.40419343 -0.07294411  2.12135945  0.40525123
 -1.27204849]


In [31]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.30698989 0.77409727 0.48652808 0.42725428 0.18213536]
 [0.65700648 0.2905624  0.97689239 0.97315315 0.98660056]
 [0.76578037 0.30661008 0.04812579 0.39116089 0.4454898 ]
 [0.68007601 0.86726295 0.81696144 0.61089724 0.01390145]
 [0.19225491 0.59980955 0.18022269 0.0346622  0.77481657]]

[[0.30698989 0.77409727 0.48652808 0.42725428 0.18213536]
 [0.65700648 0.2905624  0.97689239 0.         0.        ]
 [0.76578037 0.30661008 0.04812579 0.         0.        ]
 [0.68007601 0.86726295 0.81696144 0.61089724 0.01390145]
 [0.19225491 0.59980955 0.18022269 0.0346622  0.77481657]]


In [32]:
sub_mat = rand_mat[0:2,0:3].copy()
print(sub_mat)
sub_mat[1:,:] = 5
print(sub_mat[1:,:])
print(rand_mat)

[[0.30698989 0.77409727 0.48652808]
 [0.65700648 0.2905624  0.97689239]]
[[5. 5. 5.]]
[[0.30698989 0.77409727 0.48652808 0.42725428 0.18213536]
 [0.65700648 0.2905624  0.97689239 0.         0.        ]
 [0.76578037 0.30661008 0.04812579 0.         0.        ]
 [0.68007601 0.86726295 0.81696144 0.61089724 0.01390145]
 [0.19225491 0.59980955 0.18022269 0.0346622  0.77481657]]


In [33]:
print(rand_mat)

[[0.30698989 0.77409727 0.48652808 0.42725428 0.18213536]
 [0.65700648 0.2905624  0.97689239 0.         0.        ]
 [0.76578037 0.30661008 0.04812579 0.         0.        ]
 [0.68007601 0.86726295 0.81696144 0.61089724 0.01390145]
 [0.19225491 0.59980955 0.18022269 0.0346622  0.77481657]]


In [34]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[0.30698989 0.77409727 0.48652808 0.42725428 0.18213536]
 [0.65700648 0.2905624  0.97689239 0.         0.        ]
 [0.76578037 0.30661008 0.04812579 0.         0.        ]
 [0.68007601 0.86726295 0.81696144 0.61089724 0.01390145]
 [0.19225491 0.59980955 0.18022269 0.0346622  0.77481657]]


In [35]:
# break here for next video

In [41]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 1.04058708 -2.3349818  -1.03888703  0.11749493 -0.73591438 -0.92675233
 -0.25083125  0.21534192 -1.13688662  1.70260771  0.34433183 -0.24784786
  0.83691146 -0.49202802  0.03500588]
[ True False False  True False False False  True False  True  True False
  True False  True]
[1.04058708 0.11749493 0.21534192 1.70260771 0.34433183 0.83691146
 0.03500588]


In [42]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 1.21695756e+00 -1.18241754e-01 -9.48563952e-01 -1.52649792e+00
   4.60932134e-01]
 [-3.05635602e-01  3.64571400e-01  3.41233059e+00 -1.88684315e-01
   8.63644988e-01]
 [ 1.41127607e+00  1.45332478e+00 -2.81095333e-01  6.81504368e-01
  -6.26093855e-01]
 [ 1.40172516e-01  1.07301711e+00 -1.74393395e-01 -5.89837811e-01
  -7.56544591e-01]
 [-8.04377659e-01 -1.45935901e+00  5.93375795e-01 -1.14962623e+00
   6.11237207e-01]
 [ 2.58666004e-01  2.14524081e+00 -3.25760557e-01  8.31785062e-03
   1.74812453e+00]
 [-8.39316076e-01 -5.23431497e-01 -6.84859388e-01  1.01522307e+00
   1.98293087e-01]
 [-7.40300803e-01  2.37963283e-03 -6.01001789e-01 -3.13229859e-01
   9.01815999e-01]
 [-4.94779105e-01 -3.12077339e-01  1.63416944e+00  2.41728531e-01
   1.48447097e+00]
 [ 1.20182860e+00  1.23983295e+00  7.09147271e-01  3.77033719e-01
  -1.20061656e+00]]
[1.21695756e+00 4.60932134e-01 3.64571400e-01 3.41233059e+00
 8.63644988e-01 1.41127607e+00 1.45332478e+00 6.81504368e-01
 1.40172516e-01 1.07301711e

In [43]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 1.04058708 -2.3349818  -1.03888703  0.11749493 -0.73591438 -0.92675233
 -0.25083125  0.21534192 -1.13688662  1.70260771  0.34433183 -0.24784786
  0.83691146 -0.49202802  0.03500588]

[-5.         -2.3349818  -1.03888703  0.11749493 -0.73591438 -0.92675233
 -0.25083125  0.21534192 -1.13688662 -5.          0.34433183 -0.24784786
 -5.         -0.49202802  0.03500588]


In [44]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [51]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [52]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

#print(loaded_vec)
#print('')
print(loaded_zip)

In [53]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[0.30698989 0.77409727 0.48652808 0.42725428 0.18213536]
 [0.65700648 0.2905624  0.97689239 0.         0.        ]
 [0.76578037 0.30661008 0.04812579 0.         0.        ]
 [0.68007601 0.86726295 0.81696144 0.61089724 0.01390145]
 [0.19225491 0.59980955 0.18022269 0.0346622  0.77481657]]

[[ 1.21695756e+00 -1.18241754e-01 -9.48563952e-01 -1.52649792e+00
   4.60932134e-01]
 [-3.05635602e-01  3.64571400e-01  3.41233059e+00 -1.88684315e-01
   8.63644988e-01]
 [ 1.41127607e+00  1.45332478e+00 -2.81095333e-01  6.81504368e-01
  -6.26093855e-01]
 [ 1.40172516e-01  1.07301711e+00 -1.74393395e-01 -5.89837811e-01
  -7.56544591e-01]
 [-8.04377659e-01 -1.45935901e+00  5.93375795e-01 -1.14962623e+00
   6.11237207e-01]
 [ 2.58666004e-01  2.14524081e+00 -3.25760557e-01  8.31785062e-03
   1.74812453e+00]
 [-8.39316076e-01 -5.23431497e-01 -6.84859388e-01  1.01522307e+00
   1.98293087e-01]
 [-7.40300803e-01  2.37963283e-03 -6.01001789e-01 -3.13229859e-01
   9.01815999e-01]
 [-4.94779105e-01 -3.1207733

In [54]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[0.30698989 0.77409727 0.48652808 0.42725428 0.18213536]
 [0.65700648 0.2905624  0.97689239 0.         0.        ]
 [0.76578037 0.30661008 0.04812579 0.         0.        ]
 [0.68007601 0.86726295 0.81696144 0.61089724 0.01390145]
 [0.19225491 0.59980955 0.18022269 0.0346622  0.77481657]]

[[0.30698989 0.77409727 0.48652808 0.42725428 0.18213536]
 [0.65700648 0.2905624  0.97689239 0.         0.        ]
 [0.76578037 0.30661008 0.04812579 0.         0.        ]
 [0.68007601 0.86726295 0.81696144 0.61089724 0.01390145]
 [0.19225491 0.59980955 0.18022269 0.0346622  0.77481657]]
